services:
  - type: web
    name: whatsapp-gitbot
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
    autoDeploy: true
